### ISSUE TITLE
Wrong expected leapp destination OS version

### ISSUE THREAD

**Issue by swapdisk** [oamg/ansible-leapp#70]
Ran into this failure doing a in-place upgrade demo. Not sure where or how the role determines the expected version, but maybe need to parameterize this or make it know automatically what expected version is? I'll look deeper when I'm back in the office on Monday...

```
TASK [infra.leapp.upgrade : Validate current OS version] ***********************
fatal: [sunny-wasp]: FAILED! => {
    "assertion": "ansible_distribution_version == rhel_dest_version",
    "changed": false,
    "evaluated_to": false,
    "msg": "Expected leapp destination OS version 9.0 but OS version is 9.2."
}
Friday 02 June 2023  18:07:04 +0000 (0:00:00.066)       0:16:42.031 *********** 
```

**Comment by swapdisk** [comment]
Also looks like 7-8 upgrade now goes to 8.8 by default. Let me update the default dest versions in roles/upgrade/defaults/main.yml.

**Comment by pirat89** [comment]
@swapdisk  I think this could be problematic in future. In case of ipu 7 -> 8, the default is going to be changed (for systems without SAP) each 6months. In case of 8 -> 9, until the 8.10 release, it will be always one upgrade path 8 -> 9 for the particular minor release. So possibly you would need to implement a table, that will sa from which version to which version is expected to upgrade. 
* https://access.redhat.com/articles/4263361
* https://github.com/oamg/leapp-repository/blob/master/repos/system_upgrade/common/files/upgrade_paths.json
